---

# Specific Debian family installation tasks

- name: 'INSTALL | APT | Install Debian family dependencies'
  apt:
    name:
      - curl
      - git
      - openjdk-8-jre-headless
    state: latest
  when: "halyard_use_system_dependencies"
